# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 人淡如菊
subtitle: '不断总结，只有成长生命才有意义'
description: '愿命运 许给我们最初的温柔'
keywords: 人淡如菊，不断总结，只有成长生命才有意义
author: 谏言
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.panaihua.com
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

navbar:
  blog_title: 人淡如菊
index:
  slogan:
    enable: true
    text: 愿命运 许给我们最初的温柔
  post_url_target: _blank
  banner_img: /index_img/wallhaven2.png

post:
  banner_img: /index_img/wallhaven1.jpeg
  comments:
    enable: true
    type: valine

archive:
  banner_img: /index_img/wallhaven.png

category:
  banner_img: /index_img/wallhaven.png

tag:
  banner_img: /index_img/wallhaven.png

about:
  banner_img: /index_img/wallhaven.png

page:
  banner_img: /index_img/wallhaven.png

page404:
  banner_img: /index_img/wallhaven.png

links:
  banner_img: /index_img/wallhaven.png

lazyload:
  enable: true
  onlypost: false

footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
  content: '
    <div>
      <span id="timeDate">载入天数...</span>
      <span id="times">载入时分秒...</span>
      <script src="/js/duration.js"></script>
    </div>
  ' 

# web_analytics:  # 网页访问统计
#   enable: true # 默认为false，启用网页统计改为true即可
#   baidu: d95aaa0fb1f08b11ad55f2baeb0f2146
#   google: G-8D07XH377R

code:
  highlight:
    lib: "highlightjs"
    highlightjs:
      # 在链接中挑选 style 填入
      # Select a style in the link
      # See: https://highlightjs.org/static/demo/
      style: "Atom One Dark Reasonable"
      # 是否根据 style 改变代码背景色（如果 style 是深色背景别忘了开启此项）
      # If true, the code background will change color based on the style (If style has a dark background, don't forget to true)
      bg_color: true

custom_js: 
  - /custom/tongji.js
  - //cdn.jsdelivr.net/gh/EmoryHuang/BlogBeautify@1.1/DynamicRibbon.min.js # 动态彩带
  - //cdn.jsdelivr.net/gh/EmoryHuang/BlogBeautify@1.1/love.min.js # 鼠标点击出爱心

custom_css: 
  - /css/mac.css
custom_head: '
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-8D07XH377R"></script>
   <!-- 一言 -->
  <script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>
'
custom_html: ''

# 资源压缩
all_minifier: true
html_minifier:
  enable: true
  ignore_error: false
  exclude:
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  compress:
  exclude:
    - '*.min.js'
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false


# Valine
# 基于 LeanCloud
# Based on LeanCloud
# See: https://valine.js.org/configuration.html
valine:
  appid: LmnypknE7JdzIRpDuaayApI7-MdYXbMMI
  appkey: Gd5yMcsQPl74gn98o7Ul6aU9
  placeholder: 说点什么
  path: window.location.pathname
  avatar: retro
  meta: ['nick', 'mail', 'link']
  pageSize: 10
  lang: zh-CN
  highlight: false
  recordIP: false
  serverURLs: https://lmnypkne.api.lncldglobal.com

# 看板娘
live2d:
  model:
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
    use: live2d-widget-model-shizuku // 下载的动画模型名称
  display:
    superSample: 2
    width: 120
    height: 200
    position: right // 模型在网页显示位置,left为左,right为右
    hOffset: 20
    vOffset: 50
  mobile:
    show: false  // 移动设备是否显示,true则显示,false则不显示
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2  

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:kongjun01/panaihua.git
  branch: master